substitutions:
  _REGION: us-central1
  _SERVICE: motr-tech

options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - us-south1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/motr-technologies-inc-motr.tech/motr-tech:$COMMIT_SHA
      - .

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - us-south1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/motr-technologies-inc-motr.tech/motr-tech:$COMMIT_SHA

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - $_SERVICE
      - --image=us-south1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/motr-technologies-inc-motr.tech/motr-tech:$COMMIT_SHA
      - --region=$_REGION
      - --platform=managed
      - --allow-unauthenticated

images:
  - us-south1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/motr-technologies-inc-motr.tech/motr-tech:$COMMIT_SHA